phases:
- phase: Windows_Unit_Tests
  queue:
    matrix:
      debug:
        configuration: debug
      release: 
        configuration: release
  steps:
    - script: build/scripts/cibuild.cmd -debug -test32
           
